# Compose yaml for gitea deployment

services:
  gitea:
    image: gitea/gitea:1.27.3
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__ROOT_URL=http://10.100.100.10:3005/
      - GITEA__server__SSH_PORT=2222
      - GITEA__server__SSH_LISTEN_PORT=22
    ports:
      - "3005:3000" # Web UI - Note: Changed to 3005 to avoid conflict with Grafana on 3000 and uptime-kuma on 3001
      - "2222:22"   # SSH port for Git operations
    volumes:
      - /opt/appdata/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro